version: "3"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: digibank
      POSTGRES_USER: gotrainer
      POSTGRES_PASSWORD: verysecret
    ports:
      - "5432:5432"
    
volumes:
  database-data: